import { createFileRoute } from "@tanstack/react-router";
import { PageIntro, SiteShell } from "@/components/site-shell";
const blends=[
  {tag:"Outdoors",name:"Dengue defence",drops:"Citronella 40 · Lemongrass 30 · Lavender 20 · Clove 10",text:"Diffuse near windows at dusk. Keep it airborne only; aroma is a partial deterrent, never a replacement for removing stagnant water and using proper repellent."},
  {tag:"Haze season",name:"Haze-season clear",drops:"Eucalyptus 40 · Tea tree 25 · Peppermint 20 · Lemon 15",text:"Diffuse for 30 minutes or inhale from a tissue. It changes how air feels, but cannot filter PM2.5 — run your purifier and check NEA readings."},
  {tag:"Office life",name:"A/C headache rescue",drops:"Peppermint 35 · Lavender 35 · Frankincense 30",text:"Use as a 3% roll-on on wrists and the back of the neck, well clear of eyes. Peppermint vapour alone can make eyes water."},
  {tag:"Afternoons",name:"Humid-day energiser",drops:"Lemon myrtle 40 · Peppermint 30 · Grapefruit 15 · Ginger 15",text:"Diffuse at home or use one drop on a tissue. Keep citrus oils airborne rather than on sun-exposed skin."},
  {tag:"Evenings",name:"Evening wind-down",drops:"Lavender 40 · Bergamot FCF 30 · Cedarwood 30",text:"Diffuse 30–45 minutes before bed, or use as a 2% roll-on. Choose bergaptene-free bergamot for skin use."},
  {tag:"Deep work",name:"Deep-focus WFH",drops:"Rosemary 35 · Lemon 35 · Peppermint 30",text:"Diffuse during a focused work block, then ventilate. Keep the dose low in small rooms and pause if the aroma causes discomfort."},
];
export const Route=createFileRoute("/blends")({head:()=>({meta:[{title:"Singapore blends — Essential Oils SG"},{name:"description",content:"Six practical essential oil blends built for haze, dengue season, humid commutes and cold offices."},{property:"og:title",content:"Singapore blends — Essential Oils SG"},{property:"og:description",content:"Safety-conscious essential oil recipes tuned to everyday life in Singapore."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}),component:BlendsPage});
function BlendsPage(){return <SiteShell><PageIntro eyebrow="Six recipes · Local conditions" title="Blends tuned to this island."><p>Built for dengue season, haze weeks, freezing offices, humid commutes and the universal need to switch off at night.</p></PageIntro><section className="mx-auto grid max-w-6xl gap-4 px-6 pb-10 md:grid-cols-2">{blends.map((blend,i)=><article key={blend.name} className="rounded-[16px] bg-surface p-6 ring-1 ring-foreground/5"><div className="flex items-center justify-between gap-4"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-primary">{blend.tag}</span><span className="font-mono text-[10px] text-muted-foreground">0{i+1}</span></div><h2 className="mt-3 font-display text-2xl">{blend.name}</h2><p className="mt-4 border-y border-border py-3 font-mono text-[11px] leading-5 text-primary">{blend.drops}</p><p className="mt-4 text-sm leading-6 text-muted-foreground">{blend.text}</p></article>)}</section><aside className="mx-auto mb-20 max-w-6xl px-6"><div className="rounded-[16px] bg-primary/10 p-6 text-sm leading-6 ring-1 ring-primary/25"><strong>About the ratios:</strong> Each recipe describes a 100-drop master blend. The master blend must still be diluted for skin use. Start low when diffusing, ventilate, and read Safety 101 first.</div></aside></SiteShell>}