import { createFileRoute } from "@tanstack/react-router";
import { ShieldAlert } from "lucide-react";
import { PageIntro, SiteShell } from "@/components/site-shell";
export const Route=createFileRoute("/safety")({head:()=>({meta:[{title:"Safety 101 — Essential Oils SG"},{name:"description",content:"Essential oil dilution, patch testing and essential safety rules in one clear guide."},{property:"og:title",content:"Safety 101 — Essential Oils SG"},{property:"og:description",content:"The five-minute read that prevents almost every essential oil mistake."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}),component:SafetyPage});
const rows=[["Face, daily skincare","0.5–1%","1–3 drops"],["Body, regular use","2%","6 drops"],["Localised relief","3%","9 drops"],["Short-term, small area","5% max","15 drops"]];
function SafetyPage(){return <SiteShell><PageIntro eyebrow="Safety 101 · Five-minute read" title="Concentrated plants demand careful hands."><p>These simple rules prevent almost every essential-oil mistake. They apply to all six oils in this guide.</p></PageIntro><div className="mx-auto max-w-6xl space-y-8 px-6 pb-20">
  <section><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">The dilution chart</p><h2 className="mt-2 text-xl font-semibold">Drops per 10 ml of carrier oil</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Roughly 1% dilution equals 3 drops per 10 ml of fractionated coconut, jojoba or grapeseed oil.</p><div className="mt-5 overflow-x-auto rounded-[14px] ring-1 ring-foreground/5"><table className="w-full min-w-[580px] bg-surface text-left text-sm"><thead className="border-b border-border font-mono text-[10px] uppercase tracking-[0.14em] text-primary"><tr><th className="p-4">Use</th><th className="p-4">Dilution</th><th className="p-4">Drops per 10 ml</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row)=><tr key={row[0]}>{row.map((cell)=><td key={cell} className="p-4">{cell}</td>)}</tr>)}</tbody></table></div></section>
  <section className="rounded-[16px] bg-primary/10 p-6 ring-1 ring-primary/25"><h2 className="text-xl font-semibold">Patch-test protocol</h2><ol className="mt-5 grid gap-5 md:grid-cols-4">{["Dilute the oil exactly as you plan to use it.","Dab a small amount on your inner forearm.","Wait 24 hours — reactions can be delayed.","Redness, itching or swelling means stop."].map((step,i)=><li key={step}><span className="font-mono text-[10px] text-primary">0{i+1}</span><p className="mt-2 text-sm leading-6">{step}</p></li>)}</ol></section>
  <section className="grid gap-8 lg:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Sensitisation</p><h2 className="mt-2 text-xl font-semibold">The risk nobody warns about</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Repeated exposure can make your immune system decide an oil is a threat. From then on, trace amounts may trigger rashes for life. Oxidation makes this worse, so cap bottles tightly and replace them every 1–2 years.</p></div><div className="rounded-[16px] border border-warning/35 bg-warning/10 p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-warning" size={20}/><h2 className="text-lg font-semibold">Quick never-list</h2></div><ul className="mt-4 space-y-3 text-sm leading-6">{["Never ingest essential oils.","Never apply them undiluted to skin, hair or scalp.","Never use near eyes, inside ears or on broken skin.","Never diffuse continuously in an unventilated room.","Never treat aroma as medicine or virus protection."].map((x)=><li key={x} className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-warning"/>{x}</li>)}</ul></div></section>
  <aside className="rounded-[16px] bg-surface p-6 text-sm leading-6 text-muted-foreground ring-1 ring-foreground/5"><strong className="text-foreground">Diffusing is not risk-free.</strong> Keep sessions to 30–60 minutes, ventilate between sessions, and be cautious around babies, children, pregnant people, pets and anyone with asthma.</aside>
  <aside className="rounded-[16px] border border-border bg-warning/10 p-6 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Disclaimer.</strong> Essential Oils SG is published for entertainment and educational purposes only. The information here reflects general knowledge and personal experimentation, not clinical research or professional advice — we make no claims that any oil prevents, treats or cures any condition. Always consult a doctor or qualified practitioner before using essential oils, especially if you are pregnant, nursing, taking medication or managing a health condition.</aside>
  </div></SiteShell>}