/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlendsRouteImport } from './routes/blends'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as OilsIndexRouteImport } from './routes/oils.index'
import { Route as OilsSlugRouteImport } from './routes/oils.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlendsRoute = BlendsRouteImport.update({
  id: '/blends',
  path: '/blends',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsIndexRoute = OilsIndexRouteImport.update({
  id: '/oils/',
  path: '/oils/',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsSlugRoute = OilsSlugRouteImport.update({
  id: '/oils/$slug',
  path: '/oils/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blends': typeof BlendsRoute
  '/safety': typeof SafetyRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils/': typeof OilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blends': typeof BlendsRoute
  '/safety': typeof SafetyRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils': typeof OilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blends': typeof BlendsRoute
  '/safety': typeof SafetyRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils/': typeof OilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blends' | '/safety' | '/oils/$slug' | '/oils/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blends' | '/safety' | '/oils/$slug' | '/oils'
  id: '__root__' | '/' | '/blends' | '/safety' | '/oils/$slug' | '/oils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlendsRoute: typeof BlendsRoute
  SafetyRoute: typeof SafetyRoute
  OilsSlugRoute: typeof OilsSlugRoute
  OilsIndexRoute: typeof OilsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blends': {
      id: '/blends'
      path: '/blends'
      fullPath: '/blends'
      preLoaderRoute: typeof BlendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/': {
      id: '/oils/'
      path: '/oils'
      fullPath: '/oils/'
      preLoaderRoute: typeof OilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/$slug': {
      id: '/oils/$slug'
      path: '/oils/$slug'
      fullPath: '/oils/$slug'
      preLoaderRoute: typeof OilsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlendsRoute: BlendsRoute,
  SafetyRoute: SafetyRoute,
  OilsSlugRoute: OilsSlugRoute,
  OilsIndexRoute: OilsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
